# Swift 4.1, SwiftLint 0.25.1
reporter: xcode
opt_in_rules:
  - force_unwrapping
  - vertical_whitespace
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - first_where
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
disabled_rules:
  - todo
excluded:
  - Pods
  - vendor
  - FinalProjectTests
  - R.generated.swift
cyclomatic_complexity:
  warning: 18
line_length: 200
file_length: 1050
force_unwrapping: error
function_parameter_count:
  - 6
  - 8
function_body_length:
  - 90
  - 100
type_body_length:
  - 450
  - 500
type_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 60
identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 40
    error: 60
identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 41
    error: 60
custom_rules:
  disable:
    name: "Disable Rule In Code"
    regex: "(swiftlint:disable)"
    message: "Please do not disable rule in code. "
    severity: error
    match_kinds: comment
  outlet_collection:
    name: "outlet_collection"
    regex: "(@IBOutletCollection)"
    message: "IBOutletCollection is not permitted. "
    severity: error
  comments_space:
    name: "Add Space After Comment"
    regex: "(^\\s*//\\w+)"
    message: "There should be a space after //"
    severity: warning
    match_kinds: comment
