language: objective-c
osx_image: xcode10.2
cache:
  - bundler
  - cocoapods
xcode_workspace: MaruiMarui.xcworkspace
xcode_scheme: "FinalProject"
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 6s
before_install:
  - bundle install
  - bundle exec pod install --repo-update
install:
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
before_script:
  - chmod a+x ./scripts/add-key.sh
  - ./scripts/add-key.sh
script:
  - ./scripts/linter